name: Update README with Latest Posts

on:
  schedule:
    # Run every Sunday at 8:00 AM UTC
    - cron: '0 8 * * 0'
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ main ]
    paths: ['_posts/**'] # Only run when posts are updated

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives the action permission to write to the repo
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install front-matter
    
    - name: Update README
      run: node update-readme.js
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        # Add the node files to .gitignore if they don't exist
        echo "node_modules/" >> .gitignore
        echo "package.json" >> .gitignore
        echo "package-lock.json" >> .gitignore
        
        # Check if README.md has changes
        if git diff --quiet README.md; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected in README.md"
        else
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Changes detected in README.md"
        fi
    
    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git add .gitignore
        git commit -m "📝 Update README with latest blog posts"
        git push
        
    - name: No changes
      if: steps.verify-changed-files.outputs.changed == 'false'
      run: |
        echo "✅ README is already up-to-date with latest posts"
